## YAML Template.
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: API-USER
server:
  port: ${SERVER_PORT:5000}
amazon:
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
---
spring:
  profiles: qa
  application:
    name: API-USER
server:
  port: ${SERVER_PORT:5000}